### PR TITLE
Added Security components

### PR DESCRIPTION
**Pull request by amartinj**

### CODE REVIEW

**Comment by docteurklein** [comment]
why adding security notion in an hypermedia api ?

**Comment by mcuadros** [comment]
Hi,

This is a very old pr we just have authorication on inm as a wrapper
https://github.com/yunait/level3/tree/master/src/Level3/Processor/Wrapper/Authenticator

Just implementing staless authorication methods

Are you following the project? The documentation is very outdated, on the next weeks we will release a stable version of it.

Regards

**Comment by docteurklein** [comment]
hey there!

I just discoverd this project because I'm interested in writing hypermedia API's.
I found it using packagit.org search engine.

I know the PR is old and already merged & all, but I think it's the right place to talk about it :)

My concern is that an hypermedia library like level3 should not take care about http security problems,
since it's a REST library (not a security library).
There are more Processors about auth than about hypermedia :)

Anyway, it's just my 2 (SOC) cents.

I'll keep watching in the next weeks, and very happy to hear about a stable release!

keep up the good work :)
Flo.

**Comment by mcuadros** [comment]
Hi Flo,

Level3 try to provide all needed to make a hypemedia api, together with level3-mongator and level3-silex will make out of box apis just with one yaml definition of the database models 

As additional features you can find firewall, logger, exception handler, authentication, request limiter, following the all modern standards for stateless api

Maybe can be split in more packages but i think that is a usefull feature required for all people.

Thanks for your time is apreciated

**Comment by docteurklein** [comment]
Sure, but silex provides already a security provider (based on symfony's security component).
Wouldn't it be better to configure it instead of rewriting a full securityy layer in level3 ?

**Comment by mcuadros** [comment]
Yes in some cases we overlaps with Silex or other frameworks.

Some missing features in Silex, related to authentication, like HMAC are
implemented in Level3.

If we dont provide it and you use Level3 with Symfony, Laravel or just a
project from scratch you have to implement if by your self [1],

The Basic  authentication is just a example of how implement a
authentication header-based method  and give a point to start with your
custom authentication method as us.

But maybe i cant make a PR include HMAC to the security component. I will
check it.

[1]
http://stackoverflow.com/questions/15285217/validating-hmac-using-securityserviceprovider-with-silex

**Pull request merged**
